# Generated by Django 4.2.5 on 2023-09-12 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('criteria', models.CharField(choices=[('<', 'Lt'), ('<=', 'Lte'), ('==', 'Equal'), ('>=', 'Gte'), ('>', 'Gt')], default='==', max_length=2)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('variable', models.CharField(max_length=255)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='policies.policy')),
            ],
        ),
    ]
