# Generated by Django 4.2.5 on 2023-09-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='output',
            field=models.BooleanField(default=False),
        ),
    ]
