# Generated by Django 4.2.5 on 2023-09-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_alter_policy_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='output',
        ),
        migrations.AddField(
            model_name='policy',
            name='nodes',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
